#!groovy

properties(
    [
        [$class: 'BuildDiscarderProperty', strategy:
          [$class: 'LogRotator', artifactDaysToKeepStr: '14', artifactNumToKeepStr: '5', daysToKeepStr: '30', numToKeepStr: '60']],
        pipelineTriggers(
          [
              pollSCM('H/15 * * * *'),
              cron('@daily'),
          ]
        )
    ]
)
node {
        stage('Checkout') {
        //disable to recycle workspace data to save time/bandwidth
        deleteDir()
        checkout scm

        //enable for commit id in build number
        //env.git_commit_id = sh returnStdout: true, script: 'git rev-parse HEAD'
        //env.git_commit_id_short = env.git_commit_id.take(7)
        //currentBuild.displayName = "#${currentBuild.number}-${env.git_commit_id_short}"
        }

        //stage('Chromium install'){
           // steps{
            //    sh '''
              //  cd /home/ec2-user/
               // wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
                //sudo yum install ./google-chrome-stable_current_x86_64.rpm
                //sudo ln -s /usr/bin/google-chrome-stable /usr/bin/chromium
               // '''
           // }
       // }
        stage('NPM Install') {
        withEnv(["NPM_CONFIG_LOGLEVEL=warn"]) {
            sh '''
                cd ~/.jenkins/workspace/ui-core/RideShare
                npm install
            '''
            }
        }

        stage('Test') {
            withEnv(["CHROME_BIN=/usr/bin/chromium"]) {
            sh '''
                    cd ~/.jenkins/workspace/ui-core/RideShare
                    npm run test-headless
                '''
            }
            junit '**/test-results.xml'
        }
        // stage('Build') { 
        //   steps {
        //         sh '''
        //         cd ~/.jenkins/workspace/ui-core/RideShare
        //         ng build
        //         '''
        //   }
        // }
        // stage('Deploy'){
        //     steps{
        //         sh '''
        //         cd /home/ec2-user/.jenkins/workspace/ui-core/RideShare
        //          aws2 s3 cp --recursive ./dist s3://ui-core/angular
        //         '''
        //     }
        // }
}