#!/bin/bash

pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'echo "Hello World"'
                sh '''
                    . ~/.nvm/nvm.sh
                    echo "I am building RideShare Angular"
		    pwd
                    echo "Where is node"
                    nvm which node
                    node -v
                    npm -v
                    cd /home/ec2-user/.jenkins/workspace/ore_chore_1-PhantomJS-dependency/RideShare
		    npm install
                    ng build
                '''
            }
        }
    }
}